import Drawer from './components/Drawer'
export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Drawer></Drawer>

        {children}

      </body>
    </html>
  );
}
